[package]
name = "vulkan-tutorial"
version = "0.1.0"
authors = ["Andrey Manzharov <andreyrmg@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build-dependencies]
bindgen = "0.55.1"
